In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split 
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.ensemble import GradientBoostingRegressor, RandomForestRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import r2_score

In [2]:
# Load data
Crop_ds = pd.read_csv("crop_preprocess_ds.csv")
Crop_ds
indep_X = Crop_ds.drop('Yield/unitArea', axis=1)
dep_Y = Crop_ds['Yield/unitArea']

In [ ]:
##crop_counts = Crop_ds['Crop'].value_counts()
#Crop_ds['crop_freq_encode'] = Crop_ds['Crop'].map(crop_counts)

In [ ]:
# Frequency encoding for 'states' column
#state_counts = Crop_ds['State'].value_counts()
#Crop_ds['state_freq_encode'] = Crop_ds['State'].map(state_counts)

In [ ]:
#season_counts=Crop_ds['Season'].value_counts()
#Crop_ds['season_freq_encode']=Crop_ds['Season'].map(season_counts)

In [ ]:
#Crop_ds.drop(['Crop', 'State','Season'], axis=1, inplace=True)

In [3]:
Crop_ds

Crop_Year  Area_Hectares  Production_Tonnes  Rainfall_mm  \
0           1997        73814.0              56708       2051.4   
1           1997         6637.0               4685       2051.4   
2           1997          796.0                 22       2051.4   
3           1997        19656.0             309194       2051.4   
4           1997         1739.0                794       2051.4   
...          ...            ...                ...          ...   
19568       1998         4000.0               2000       1498.0   
19569       1998         1000.0               3000       1498.0   
19570       1997       187823.5             309194       1356.2   
19571       1997       187823.5               5488       1356.2   
19572       1997       187823.5             309194       1356.2   

       Fertilizer_Kgms  Pesticide_Kgms  Crop_Arhar/Tur  Crop_Bajra  \
0           7024878.38        22882.34               0           0   
1            631643.29         2057.47               1           0   
2             75755.32          246.76               0           0   
3           1870661.52         6093.36               0           0   
4            165500.63          539.09               0           0   
...                ...             ...             ...         ...   
19568        395200.00         1160.00               0           0   
19569         98800.00          290.00               0           0   
19570      25054187.10        49993.35               0           0   
19571      25054187.10        49993.35               0           0   
19572      22778368.48        49993.35               0           0   

       Crop_Banana  Crop_Barley  ...  State_Puducherry  State_Punjab  \
0                0            0  ...                 0             0   
1                0            0  ...                 0             0   
2                0            0  ...                 0             0   
3                0            0  ...                 0             0   
4                0            0  ...                 0             0   
...            ...          ...  ...               ...           ...   
19568            0            0  ...                 0             0   
19569            0            0  ...                 0             0   
19570            0            0  ...                 0             0   
19571            0            0  ...                 0             0   
19572            0            0  ...                 0             0   

       State_Sikkim  State_Tamil Nadu  State_Telangana  State_Tripura  \
0                 0                 0                0              0   
1                 0                 0                0              0   
2                 0                 0                0              0   
3                 0                 0                0              0   
4                 0                 0                0              0   
...             ...               ...              ...            ...   
19568             0                 0                0              0   
19569             0                 0                0              0   
19570             0                 0                0              0   
19571             0                 0                0              0   
19572             0                 0                0              0   

       State_Uttar Pradesh  State_Uttarakhand  State_West Bengal  \
0                        0                  0                  0   
1                        0                  0                  0   
2                        0                  0                  0   
3                        0                  0                  0   
4                        0                  0                  0   
...                    ...                ...                ...   
19568                    0                  0                  0   
19569                    0                  0                  0   
19570  

In [ ]:
indep_X

In [ ]:
dep_Y

In [4]:
# Split data and standardize
X_train, X_test, y_train, y_test = train_test_split(indep_X, dep_Y, test_size=0.25, random_state=0)
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [5]:
# PCA
pca = PCA(n_components=12)
X_train_PCA = pca.fit_transform(X_train_scaled)
X_test_PCA = pca.transform(X_test_scaled)

In [6]:
# Model Evaluation Functions
def r2_prediction(regressor, X_test, y_test):
    y_pred = regressor.predict(X_test)
    r2 = r2_score(y_test, y_pred)
    return r2

# Model Training Functions
def Decision(X_train, y_train, X_test, y_test):
    regressor = DecisionTreeRegressor(random_state=0)
    regressor.fit(X_train, y_train)
    r2 = r2_prediction(regressor, X_test, y_test)
    return r2

def random(X_train, y_train, X_test, y_test):
    regressor = RandomForestRegressor(n_estimators=10, random_state=0)
    regressor.fit(X_train, y_train)
    r2 = r2_prediction(regressor, X_test, y_test)
    return r2

def gradient(X_train, y_train, X_test, y_test):
    regressor = GradientBoostingRegressor(random_state=0)
    regressor.fit(X_train, y_train)
    r2 = r2_prediction(regressor, X_test, y_test)
    return r2



In [7]:
acc_decision = Decision(X_train_PCA, y_train, X_test_PCA, y_test)
acc_random = random(X_train_PCA, y_train, X_test_PCA, y_test)
acc_gradient = gradient(X_train_PCA, y_train, X_test_PCA, y_test)

In [8]:
# Display results
result = pd.DataFrame(index=['n=12'], columns=['DecisionTree', 'RandomForest', 'GradientBoosting'])
result.loc['n=12', 'DecisionTree'] = acc_decision
result.loc['n=12', 'RandomForest'] = acc_random
result.loc['n=12', 'GradientBoosting'] = acc_gradient


In [9]:
print(result)

     DecisionTree RandomForest GradientBoosting
n=12     0.707988     0.842753         0.626578


In [10]:
X_train_PCA.shape

(14679, 12)

In [11]:
y_train.shape

(14679,)

In [12]:
components = pca.components_

In [13]:
components_df = pd.DataFrame(components, columns=X_train.columns)

In [14]:
components_df

Crop_Year  Area_Hectares  Production_Tonnes  Rainfall_mm  Fertilizer_Kgms  \
0   -0.031664       0.463473           0.418637    -0.184927         0.463146   
1   -0.094436       0.040786           0.157370     0.322851         0.037857   
2    0.025847       0.010621           0.015693    -0.021908         0.013883   
3    0.021625       0.060143           0.013127     0.489721         0.060955   
4    0.071083      -0.052009          -0.032832    -0.119360        -0.049235   
5    0.308929      -0.002663          -0.001093     0.063993         0.014004   
6    0.055941      -0.006479           0.025675     0.028917        -0.001826   
7    0.090751       0.001629          -0.016939     0.021828         0.007396   
8   -0.225629      -0.036060           0.059603    -0.006169        -0.048398   
9    0.068406      -0.040505           0.064956    -0.033820        -0.037937   
10  -0.131007      -0.003690          -0.032354     0.011821        -0.009662   
11  -0.048445      -0.007215          -0.036425    -0.016619        -0.011231   

    Pesticide_Kgms  Crop_Arhar/Tur  Crop_Bajra  Crop_Banana  Crop_Barley  ...  \
0         0.461530        0.011886    0.032211    -0.003794    -0.016537  ...   
1         0.037980       -0.064050   -0.069223     0.152777    -0.067626  ...   
2         0.010889       -0.082626   -0.096210    -0.016072     0.108699  ...   
3         0.062998        0.058259   -0.080398    -0.061226    -0.039354  ...   
4        -0.050061       -0.117548    0.006165     0.012604    -0.059989  ...   
5         0.009650        0.018433   -0.004366     0.036064    -0.121622  ...   
6        -0.003502       -0.070797    0.039883    -0.011911     0.092315  ...   
7         0.005056       -0.012372   -0.072323    -0.148974     0.002450  ...   
8        -0.045652        0.029549    0.129254     0.157620    -0.090371  ...   
9        -0.037665        0.077102    0.070792    -0.018498     0.032138  ...   
10       -0.008855        0.089645    0.214095    -0.097928     0.195318  ...   
11       -0.008566       -0.020671    0.203661    -0.043549    -0.214083  ...   

    State_Odisha  State_Puducherry  State_Punjab  State_Sikkim  \
0      -0.006190         -0.067031      0.026364     -0.042428   
1       0.011332          0.001013     -0.100411      0.001816   
2      -0.025737         -0.043154      0.012924     -0.021409   
3       0.148858         -0.047789     -0.079379      0.119560   
4       0.485994          0.130332     -0.023204     -0.096095   
5      -0.218336          0.187108     -0.048658     -0.040117   
6      -0.016718         -0.220734     -0.116565      0.115290   
7      -0.137753          0.009487     -0.040843     -0.181430   
8      -0.090348          0.022930      0.102918     -0.105523   
9      -0.045782          0.013142     -0.065508     -0.036280   
10     -0.067515          0.093071      0.276717      0.123256   
11     -0.001938         -0.084851      0.182705     -0.181494   

    State_Tamil Nadu  State_Telangana  State_Tripura  State_Uttar Pradesh  \
0           0.032088        -0.009163      -0.050790             0.074967   
1           0.067819        -0.077733      -0.017854            -0.075655   
2          -0.024266         0.011738      -0.002490             0.019472   
3          -0.198583        -0.028503       0.188038            -0.076634   
4          -0.037822         0.033356      -0.071410             0.045454   
5           0.001745         0.239719       0.039351             0.095720   
6          -0.047131        -0.026191      -0.092723             0.204269   
7          -0.047374         0.083915       0.094421             0.116025   
8          -0.204277        -0.226320      -0.059965             0.238751   
9           0.049998         0.113759       0.019435            -0.059025   
10         -0.005945        -0.156272       0.069548             0.122637   
11          0.080513         0.053032      -0.024328            -0.248218   

    State_Uttarakhand  State_West B

In [15]:
top_features_indices = [component.argsort()[-2:][::-1] for component in components]  # Assuming you want the top 3 contributing features

In [16]:
top_features_indices

[array([1, 4], dtype=int64),
 array([63,  3], dtype=int64),
 array([61, 58], dtype=int64),
 array([ 3, 81], dtype=int64),
 array([84, 62], dtype=int64),
 array([ 0, 62], dtype=int64),
 array([65, 35], dtype=int64),
 array([65, 35], dtype=int64),
 array([66, 91], dtype=int64),
 array([69, 25], dtype=int64),
 array([86, 22], dtype=int64),
 array([71, 35], dtype=int64)]

In [17]:
selected_input_variables = []
for indices in top_features_indices:
    selected_input_variables.append([X_train.columns[i] for i in indices])

In [18]:
print(selected_input_variables)


[['Area_Hectares', 'Fertilizer_Kgms'], ['Season_Whole Year ', 'Rainfall_mm'], ['Season_Rabi       ', 'Crop_Wheat'], ['Rainfall_mm', 'State_Meghalaya'], ['State_Odisha', 'Season_Summer     '], ['Crop_Year', 'Season_Summer     '], ['State_Arunachal Pradesh', 'Crop_Oilseeds total'], ['State_Arunachal Pradesh', 'Crop_Oilseeds total'], ['State_Assam', 'State_Uttar Pradesh'], ['State_Delhi', 'Crop_Jowar'], ['State_Punjab', 'Crop_Groundnut'], ['State_Gujarat', 'Crop_Oilseeds total']]


In [19]:
from collections import Counter
flattened_features = [feature for sublist in selected_input_variables for feature in sublist]
feature_counts = Counter(flattened_features)
top_features = feature_counts.most_common(5)  # Change 5 to the desired number of top features
top_feature_names = [feature[0] for feature in top_features]
print(top_feature_names)


['Crop_Oilseeds total', 'Rainfall_mm', 'Season_Summer     ', 'State_Arunachal Pradesh', 'Area_Hectares']


In [20]:
X_train_selected = X_train[top_feature_names]


In [21]:
X_train_selected

Crop_Oilseeds total  Rainfall_mm  Season_Summer       \
4696                     0       1201.9                   0   
4676                     0       1201.9                   0   
14251                    0       1223.2                   0   
13356                    0       1348.7                   0   
17037                    0       1031.7                   0   
...                    ...          ...                 ...   
9225                     0        907.8                   1   
13123                    0       1216.9                   0   
9845                     0       1362.5                   0   
10799                    0        891.6                   0   
2732                     0       1201.9                   0   

       State_Arunachal Pradesh  Area_Hectares  
4696                         0       187823.5  
4676                         0        19796.0  
14251                        0         8326.0  
13356                        0        49638.0  
17037                        0           63.0  
...                        ...            ...  
9225                         0       163458.0  
13123                        0         3408.0  
9845                         0         1000.0  
10799                        0       187823.5  
2732                         0       124301.0  

[14679 rows x 5 columns]

In [22]:
X_train_selected.shape

(14679, 5)

In [23]:
X_test_selected = X_test[top_feature_names]


In [24]:
X_test_selected

Crop_Oilseeds total  Rainfall_mm  Season_Summer       \
19137                    0       1503.4                   0   
5027                     0        912.4                   0   
11685                    0       1771.8                   0   
12493                    0       1366.8                   0   
763                      0        928.4                   0   
...                    ...          ...                 ...   
15305                    0       1112.0                   0   
15132                    0        965.3                   0   
9355                     0        516.9                   0   
6876                     0       1484.3                   0   
1578                     0       2698.2                   0   

       State_Arunachal Pradesh  Area_Hectares  
19137                        0         5786.0  
5027                         0        76420.0  
11685                        0        27050.0  
12493                        0       101457.0  
763                          0       104244.0  
...                        ...            ...  
15305                        0         8587.0  
15132                        0       187823.5  
9355                         0          127.0  
6876                         0       187823.5  
1578                         0         1472.0  

[4894 rows x 5 columns]

In [25]:
y_train.shape

(14679,)

In [28]:
from sklearn.model_selection import GridSearchCV

In [26]:

def grid_search_models(X_train_selected, y_train):
    models = {
        "RandomForestRegressor": (RandomForestRegressor(), {
            'criterion': ['squared_error', 'absolute_error'],
            'max_features': ['sqrt', 'log2'],
            'n_estimators': [10, 100]
        }),
        "DecisionTreeRegressor": (DecisionTreeRegressor(), {
            'criterion': ['squared_error', 'absolute_error'],
            'splitter':['best','random'],
            'max_features': ['sqrt','log2']
        })
        #"GradientBoostingRegressor":(GradientBoostingRegressor(), {
          #'criterion': ['friedman_mse', 'squared_error'],
            #'n_estimators':[10,100]
        #})
    }

    results = {}
    
    for model_name, (model, param_grid) in models.items():
        grid_search = GridSearchCV(model, param_grid, refit=True, verbose=3, n_jobs=-1)  
        
        grid_search.fit(X_train_selected, y_train)
        
        results[model_name] = {
            "Best parameters": grid_search.best_params_,
            "Best score": grid_search.best_score_
        }

    return results


In [29]:
results = grid_search_models(X_train_selected,y_train)
print(results)

Fitting 5 folds for each of 8 candidates, totalling 40 fits
Fitting 5 folds for each of 8 candidates, totalling 40 fits
{'RandomForestRegressor': {'Best parameters': {'criterion': 'absolute_error', 'max_features': 'sqrt', 'n_estimators': 100}, 'Best score': -0.05687288988146495}, 'DecisionTreeRegressor': {'Best parameters': {'criterion': 'absolute_error', 'max_features': 'log2', 'splitter': 'random'}, 'Best score': -0.6956751862174293}}


In [ ]:
best_model_name, best_score = max((model_name, results[model_name]['Best score']) for model_name in results)

In [ ]:
best_model_name, best_score

In [ ]:
best_params = results[best_model_name]['Best parameters']

In [ ]:
best_params

In [ ]:
X_train_selected.shape

In [ ]:
y_train.shape

In [ ]:
X_test_selected.shape

In [ ]:
y_test.shape

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X_train_PCA, y_train, test_size=0.25, random_state=42)

In [ ]:
best_model=RandomForestRegressor(**best_params)
best_model.fit(X_train_selected,y_train)